"""Central timing configuration for runtime mapping and menu exploration."""

DEFAULT_UI_DELAY = 0.2
POPUP_OPEN_DELAY = 0.25
BASELINE_DELAY = 0.3
WINDOW_READY_TIMEOUT = 1.2
WINDOW_READY_POLL_INTERVAL = 0.05
POPUP_WAIT_TIMEOUT = 0.8
POPUP_WAIT_POLL_INTERVAL = 0.05
POPUP_CLOSE_TIMEOUT = 0.5
